### ISSUE TITLE
Very long file paths

### ISSUE THREAD

**Issue by aquamoth** [jamesshore/automatopia#4]
The file paths get very long in this project because node_modules have node-modules that ... have node_modules... :/

While I get around the limitation of that in Windows, I just don't understand if this kind of setup is a requirement for node modules, or if it is just because you want to track dependencies?

If you care to summarize the reason for it I'd much appreciate it. 

PS. I'm forking automatopia to create a requirejs-version of it. It's just awesome :)

**Comment by jamesshore** [comment]
It's because I want to track dependencies. See [The Reliable Build](http://www.letscodejavascript.com/v3/blog/2014/12/the_reliable_build) for more.

Current versions of Node flatten the node_modules directory, so this problem isn't as big of an issue. Next time I refresh the dependencies, I'll also upgrade the version of Node and flatten the paths.

PS: Thanks! Glad you like it :-)

**Comment by jamesshore** [comment]
Automatopia no longer vendors node_modules, so this issue is resolved.
